{% set name = "dealii" %}
{% set version = "9.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://dealii.kyomu.43-1.org/downloads/dealii-{{ version }}.tar.gz
  sha256: 5dfb59174b341589e92b434398a1b7cc11ad053ce2315cf673f5efc5ba271a29

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
  host:
    - zlib
    - tbb-devel
    - muparser
    - python
    - boost
  run:
    - zlib
    - tbb
    - {{ pin_compatible("muparser") }}
    - python
    - boost

test:
  imports:
    - PyDealII
  requires:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - tbb-devel

about:
  home: https://dealii.org/
  license: LGPL-2.1-or-later
  license_file: LICENSE.md
  summary: The deal.ii finite element package

  description: |
    deal.II is a C++ program library targeted at the computational solution of
    partial differential equations using adaptive finite elements. It uses
    state-of-the-art programming techniques to offer you a modern interface to
    the complex data structures and algorithms required.
  doc_url: https://dealii.org/current/doxygen/deal.II/Tutorial.html
  dev_url: https://github.com/dealii/dealii

extra:
  recipe-maintainers:
    - inducer
    - xywei
