{% set name = "dealii" %}
{% set version = "9.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dealii/dealii/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ee7a6f98c1d8515fbd68b5fa7df46cb033efcabc87848a8a322d48f4d1e46676

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
  host:
    - zlib
    - tbb-devel
    - muparser
    - python
    - libboost-python-devel
  run:
    - zlib
    - tbb
    - {{ pin_compatible("muparser") }}
    - python
    - libboost-python-devel

test:
  imports:
    - PyDealII
  requires:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - tbb-devel

about:
  home: https://dealii.org/
  license: LGPL-2.1-or-later
  license_file: LICENSE.md
  summary: The deal.ii finite element package

  description: |
    deal.II is a C++ program library targeted at the computational solution of
    partial differential equations using adaptive finite elements. It uses
    state-of-the-art programming techniques to offer you a modern interface to
    the complex data structures and algorithms required.
  doc_url: https://dealii.org/current/doxygen/deal.II/Tutorial.html
  dev_url: https://github.com/dealii/dealii

extra:
  recipe-maintainers:
    - inducer
    - xywei
