{% set name = "dealii" %}
{% set version = "9.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dealii/dealii/releases/download/v{{ version }}/dealii-{{ version }}.tar.gz
  sha256: 1051e332de3822488e91c2b0460681052a3c4c5ac261cdd7a6af784869a25523

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - kokkos
    - python {{ python }}
  host:
    - zlib
    - libblas
    - liblapack
    - tbb-devel
    - muparser
    - python {{ python }}
    - libboost-devel
    - libboost-python-devel
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - tbb-devel
  run:
    - zlib
    - tbb
    - {{ pin_compatible("muparser") }}
    - python {{ python }}

test:
  imports:
    - PyDealII

about:
  home: https://dealii.org/
  license: LGPL-2.1-or-later
  license_file: LICENSE.md
  summary: The deal.ii finite element package

  description: |
    deal.II is a C++ program library targeted at the computational solution of
    partial differential equations using adaptive finite elements. It uses
    state-of-the-art programming techniques to offer you a modern interface to
    the complex data structures and algorithms required.
  doc_url: https://dealii.org/current/doxygen/deal.II/Tutorial.html
  dev_url: https://github.com/dealii/dealii

extra:
  recipe-maintainers:
    - inducer
    - xywei
